currency_master:
  primary_key: [currency_id]

supplier_master:
  primary_key: [supplier_id]

material_type_master:
  primary_key: [material_type_master_id]

uom_master:
  primary_key: [uom_id]

location_type_master:
  primary_key: [location_type_id]

location_master:
  primary_key: [location_id]

calendar_master:
  primary_key: [date]

frequency_master:
  primary_key: [frequency_of_update_id]

repeat_master:
  primary_key: [repeat_master_id]

purchasing_organizations:
  primary_key: [purchasing_org_id]

port_master:
  primary_key: [port_id]

material_master:
  primary_key: [material_id]

purchaser_plant_master:
  primary_key: [plant_id]

pricing_source_master:
  primary_key: [source_of_price_id]

where_to_use_each_price_type:
  primary_key: [porg_material_price_type_id]

news_tags:
  primary_key: [news_tag_id]

pricing_type_master:
  primary_key: [price_type_id]

tile_cost_sheet_chemical_reaction_master_data:
  primary_key: [m_cr_rrm_id]

currency_exchange_history:
  primary_key: [currency_exchange_id]

user_currency_preference:
  primary_key: [user_id]

incoterms_master:
  primary_key: [incoterm_id]

plant_material_purchase_org_supplier:
  primary_key: [porg_plant_material_id]

forex_conversion_options_master:
  primary_key: [forex_conversion_id]

settings_user_material_category:
  primary_key: [user_material_category_id]

uom_conversion:
  primary_key: [id]

# New Master Tables
admin_user:
  primary_key: [id]

country_master:
  primary_key: [country_id]

chemical_raw_material_synonyms:
  primary_key: [material_synonym_id]

user_master:
  primary_key: [user_id]

# New Relationship Tables
user_purchase_org:
  primary_key: [user_purchase_org_id]

company_currency_exchange_history:
  primary_key: [currency_exchange_purchase_org_id]

country_hsn_code_wise_duty_structure:
  primary_key: [id]

country_tariffs:
  primary_key: [id]

ocean_freight_master:
  primary_key: [ocean_freight_id]

plant_to_port_mapping_master:
  primary_key: [plant_port_id]

supplier_hierarchy:
  primary_key: [supplier_hierarchy_id]

# New Transactional Tables
action_plans:
  primary_key: [id]

audit_snapshot_price_prediction_negotiation:
  primary_key: [porg_plant_material_date_id]

demand_supply_summary:
  primary_key: [id]

demand_supply_trends:
  primary_key: [id]

esg_tracker:
  primary_key: [id]

export_data:
  primary_key: [id]

fact_pack:
  primary_key: [id]

forecast_recommendations:
  primary_key: [id]

import_data:
  primary_key: [id]

inventory_levels:
  primary_key: [id]

joint_development_projects:
  primary_key: [id]

material_research_reports:
  primary_key: [id]

material_supplier_general_intelligence:
  primary_key: [material_supplier_general_intelligence_id]

material_synonyms:
  primary_key: [synonym_id]

meeting_minutes:
  primary_key: [id]

multiple_point_engagements:
  primary_key: [id]

negotiation_llm_logs:
  primary_key: [id]

negotiation_recommendations:
  primary_key: [id]

news_insights:
  primary_key: [id]

news_porg_plant_material_source_data:
  primary_key: [news_porg_plant_material_source_data_id]

plan_assignments:
  primary_key: [id]

porters_analysis:
  primary_key: [id]

price_data_country_storage:
  primary_key: [material_plant_id]

price_forecast_data:
  primary_key: [forecast_id]

price_history_data:
  primary_key: [material_price_type_period_id]

procurement_plans:
  primary_key: [id]

purchase_history_transactional_data:
  primary_key: [purchase_transaction_id]

quote_comparison:
  primary_key: [id]

reach_tracker:
  primary_key: [id]

region_hierarchy:
  primary_key: [synonym_id]

settings_user_material_category_tile_preferences:
  primary_key: [user_material_category_id]

supplier_shutdowns:
  primary_key: [id]

supplier_tracking:
  primary_key: [id]

tile_cost_sheet_historical_current_supplier:
  primary_key: [porg_plant_material_supplier_date]

tile_multiple_point_engagements:
  primary_key: [porg_plant_material_supplier_date]

tile_vendor_minutes_of_meeting:
  primary_key: [porg_plant_material_supplier_date]

vendor_key_information:
  primary_key: [id]

vendor_wise_action_plan:
  primary_key: [id]

market_research_status:
  primary_key: [id]

tiles:
  primary_key: [id]


